version: '3.9'

services:
  # MongoDB Service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes: 
      - mongo_data:/data/db
  
  # Node Api Service
  api:
    build: .
    ports:     
      - 4000:6000
    environment:
      PORT: 6000
      MONGODB_URL: mongodb://127.0.0.1:27017/alarmsdb      
    depends_on:
      -  mongo_db
volumes:
  mongo_data: {}
    